name: Demo Workflow
on: [workflow_dispatch]
jobs: 
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Step_1
        run: echo Hello world of GitHub Actions!
      - name: Step_2
        run: |
          echo First line
          echo Second line
